spring:
  application.name: myshield-user-api
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    # Spring JDBC configuration
  datasource:
    url: jdbc:mysql://localhost:3306/mybank?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=IST
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    properties:
      javax.persistence.validation.mode: none
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 80

mybank:
  officehours-start-time: '9 AM'
  officehours-close-time: '6 PM'
  account:
    type-codes:
      - 0
      - 1
      - 2
    min-balance: 1000